version: '2'

networks:
  mongodb:
    driver: bridge

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - mongodb

# services:
#   db:
#     image: postgres:14.1-alpine
#     container_name: 'postgres'
#     restart: always
#     # restart: on-failure
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=postgres
#     ports:
#       - '5432:5432'
#     networks:
#       - postgres-base-net

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
